environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    SDL_TARGET: lib\x64
    SDL_COPY_PATTERN: SDL2*.lib
  - TARGET: i686-pc-windows-msvc
    SDL_TARGET: lib\x86
    SDL_COPY_PATTERN: SDL2*.lib
  - TARGET: i686-pc-windows-gnu
    SDL_TARGET: i686-w64-mingw32\lib
    SDL_COPY_PATTERN: libSDL2*
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - ps: Start-FileDownload "https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz"
  - ps: 7z x SDL2-devel-2.0.4-mingw.tar.gz
  - ps: 7z x SDL2-devel-2.0.4-mingw.tar
  - ps: Copy-Item "SDL2-2.0.4\${env:SDL_TARGET}\${env:SDL_COPY_PATTERN}" "C:\Program Files (x86)\Rust\lib\rustlib\${env:TARGET}\lib\"
  - rustc -V
  - cargo -V
build: false

test_script:
  - ps: New-Item c:\projects\rust64\target -type directory
  - ps: New-Item c:\projects\rust64\target\debug -type directory
  - ps: Copy-Item SDL2-2.0.4\i686-w64-mingw32\lib\libSDL2.dll.a c:\projects\rust64\target\debug
  - cargo test --verbose